### ISSUE TITLE
Species search hamburger icon is unresponsive initially

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2575]
In order to view the alphabetical list of species in full (as a dropdown), you must start to type in the species search box. Subsequently deleting your query, the hamburger icon becomes responsive and will display the list.

**Comment by jmorrison1847** [comment]
Discovered by @RickMohr 
Clicking the hamburger icon before typing in the search box:
<img width="1280" alt="screen shot 2016-05-05 at 2 28 08 pm" src="https://cloud.githubusercontent.com/assets/12401491/15052870/c98ad7ca-12cd-11e6-9d64-833aa80b7ce5.png">
Nothing happens.

Type something:
<img width="1280" alt="screen shot 2016-05-05 at 2 28 16 pm" src="https://cloud.githubusercontent.com/assets/12401491/15052868/c985f30e-12cd-11e6-8513-2a55b239cec1.png">
A sub-list appears.

Delete the text, and the button is active in full:
<img width="1280" alt="screen shot 2016-05-05 at 2 28 23 pm" src="https://cloud.githubusercontent.com/assets/12401491/15052869/c98a0dcc-12cd-11e6-8633-3d65de92e0e9.png">

**Comment by mmcfarland** [comment]
I believe this is fixed on current develop.  Clicking the hamburger or focusing the search box will drop the menu down prior to any text being typed in.  I can reproduced the described behavior on current production.  Is there an easy way to see what sha version production corresponds to?

**Comment by maurizi** [comment]
@mmcfarland We're using git flow, so based on the master branch I think the current production SHA is 10f81ed848828a176a97d1a389896bd3e59d02cf

**Comment by RickMohr** [comment]
Still a problem on production, with both the Species and Location search boxes.

However, the problem doesn't happen if you load a map, wait a bit, and then reload the page. Since we keep the latest map's autocomplete lists in browser-local storage, it smells like a race condition -- things initialize correctly when fetching the autocomplete list from browser-local storage, but not when fetching via AJAX.

**Comment by jwalgran** [comment]
We removed the hamburger button. The species list now appears when the field is focused.
